export const STATIC_EMOJI = {
  bic_check_mark: require('../../assets/emoji/static/bic_check_mark.png'),
  bic_clapping_hands: require('../../assets/emoji/static/bic_clapping_hands.png'),
  bic_clinking_beer_mugs: require('../../assets/emoji/static/bic_clinking_beer_mugs.png'),
  bic_clinking_glasses: require('../../assets/emoji/static/bic_clinking_glasses.png'),
  bic_crown: require('../../assets/emoji/static/bic_crown.png'),
  bic_fire: require('../../assets/emoji/static/bic_fire.png'),
  bic_flag: require('../../assets/emoji/static/bic_flag.png'),
  bic_glowing_star: require('../../assets/emoji/static/bic_glowing_star.png'),
  bic_handshake: require('../../assets/emoji/static/bic_handshake.png'),
  bic_heart: require('../../assets/emoji/static/bic_heart.png'),
  bic_heart_exclamation: require('../../assets/emoji/static/bic_heart_exclamation.png'),
  bic_heart_gift: require('../../assets/emoji/static/bic_heart_gift.png'),
  bic_hugging_face: require('../../assets/emoji/static/bic_hugging_face.png'),
  bic_hundred_points: require('../../assets/emoji/static/bic_hundred_points.png'),
  bic_light_bulb: require('../../assets/emoji/static/bic_light_bulb.png'),
  bic_money_mouth_face: require('../../assets/emoji/static/bic_money_mouth_face.png'),
  bic_money_with_wings: require('../../assets/emoji/static/bic_money_with_wings.png'),
  bic_muscle_diamond: require('../../assets/emoji/static/bic_muscle_diamond.png'),
  bic_partying_face: require('../../assets/emoji/static/bic_partying_face.png'),
  bic_raising_hands: require('../../assets/emoji/static/bic_raising_hands.png'),
  bic_revolving_hearts: require('../../assets/emoji/static/bic_revolving_hearts.png'),
  bic_screaming: require('../../assets/emoji/static/bic_screaming.png'),
  bic_smiling_face_with_heart_eyes: require('../../assets/emoji/static/bic_smiling_face_with_heart_eyes.png'),
  bic_sparkling_heart: require('../../assets/emoji/static/bic_sparkling_heart.png'),
  bic_star_struck: require('../../assets/emoji/static/bic_star_struck.png'),
  bic_text: require('../../assets/emoji/static/bic_text.png'),
  bic_text_x10k: require('../../assets/emoji/static/bic_text_x10k.png'),
  bic_thumbs_up: require('../../assets/emoji/static/bic_thumbs_up.png'),
  bic_tothemoon: require('../../assets/emoji/static/bic_tothemoon.png'),
  bic_trophy: require('../../assets/emoji/static/bic_trophy.png'),
  bic_unicorn: require('../../assets/emoji/static/bic_unicorn.png'),
  bic_violet: require('../../assets/emoji/static/bic_violet.png'),
  bic_violet_moon: require('../../assets/emoji/static/bic_violet_moon.png'),
  bic_warning: require('../../assets/emoji/static/bic_warning.png'),
  bic_writing_hand: require('../../assets/emoji/static/bic_writing_hand.png'),
  bic_x10k: require('../../assets/emoji/static/bic_x10k.png'),
};

export const ANIMATED_EMOJI = {
  bic_airplane: require('../../assets/emoji/animated/bic_airplane.gif'),
  bic_diamond: require('../../assets/emoji/animated/bic_diamond.gif'),
  bic_direct_hit: require('../../assets/emoji/animated/bic_direct_hit.gif'),
  bic_fireworks: require('../../assets/emoji/animated/bic_fireworks.gif'),
  bic_flying_rocket: require('../../assets/emoji/animated/bic_flying_rocket.gif'),
  bic_globe: require('../../assets/emoji/animated/bic_globe.gif'),
  bic_growing_heart: require('../../assets/emoji/animated/bic_growing_heart.gif'),
  bic_party_popper: require('../../assets/emoji/animated/bic_party_popper.gif'),
  bic_purple_heart: require('../../assets/emoji/animated/bic_purple_heart.gif'),
  bic_smiling_face_with_hearts: require('../../assets/emoji/animated/bic_smiling_face_with_hearts.gif'),
  bic_sparkles: require('../../assets/emoji/animated/bic_sparkles.gif'),
  bic_whale: require('../../assets/emoji/animated/bic_whale.gif'),
};
