export const SET_MODAL = 'common/SET_MODAL';
export const SHOW_MODAL = 'common/SHOW_MODAL';
export const HIDE_MODAL = 'common/HIDE_MODAL';

export const SHOW_ALERT_NEW_FEATURE = 'common/SHOW_ALERT_NEW_FEATURE';
export const HIDE_ALERT_NEW_FEATURE = 'common/HIDE_ALERT_NEW_FEATURE';
export const SHOW_LOADING = 'common/SHOW_LOADING';
export const HIDE_LOADING = 'common/HIDE_LOADING';

export const FOCUS_SEARCH_INPUT = 'common/FOCUS_SEARCH_INPUT';

export const SHOW_REACTION_DETAIL_BOTTOM_SHEET = 'common/SHOW_REACTION_DETAIL_BOTTOM_SHEET';
export const CLEAR_REACTION_DETAIL_BOTTOM_SHEET = 'common/CLEAR_REACTION_DETAIL_BOTTOM_SHEET';

export const SET_SHOW_REACTION_BOTTOM_SHEET = 'common/SET_SHOW_REACTION_BOTTOM_SHEET';

export const SHOW_SEEN_PEOPLE_LIST_BOTTOM_SHEET = 'common/SHOW_SEEN_PEOPLE_LIST_BOTTOM_SHEET';

export const SHOW_BOTTOM_LIST = 'common/SHOW_BOTTOM_LIST';
export const SET_BOTTOM_LIST = 'common/SET_BOTTOM_LIST';
export const HIDE_BOTTOM_LIST = 'common/HIDE_BOTTOM_LIST';
