/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-southeast-1',
  aws_cognito_identity_pool_id:
    'ap-southeast-1:c158f335-c3ed-480d-871c-dc672bde36ed',
  aws_cognito_region: 'ap-southeast-1',
  aws_user_pools_id: 'ap-southeast-1_ItbxQt1Q9',
  aws_user_pools_web_client_id: '1r4t1daaqm2k7m4b2i86drt4cu',
  oauth: {
    domain: 'bein.auth.ap-southeast-1.amazoncognito.com',
    responseType: 'token',
    scope: ['email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
    redirectSignIn: 'bein-app://',
    redirectSignOut: 'bein-app://',
  },
};

export default awsmobile;
