export const responseAddWorkExperience = {
  code: 'api.ok',
  meta: { message: 'Success' },
  data: {
    id: '7536a432-2d7a-4a54-bef1-e541fd498541',
    userId: '97f3a300-97ee-4d9d-bc3e-3a8724d9d511',
    company: 'test',
    location: 'test',
    titlePosition: 'test',
    description: 'test',
    currentlyWorkHere: true,
    startDate: '2022-02-09T17:00:00.000Z',
    endDate: null,
    updatedAt: '2023-02-10T10:30:17.193Z',
    createdAt: '2023-02-10T10:30:17.193Z',
    deletedAt: null,
  },
};

export const responseEditWorkExperience = { code: 'api.ok', meta: { message: 'Success' }, data: true };

export const responseDeleteWorkExperience = { code: 'api.ok', meta: { message: 'Success' }, data: [] };

export const responseGetUserProfile = {
  code: 'api.ok',
  meta: { message: 'Success' },
  data: {
    id: '97f3a300-97ee-4d9d-bc3e-3a8724d9d511',
    chatUserId: 'stzuazhpijrfie5dhpr338e6xo',
    email: 'anhquoc1@mailinator.com',
    username: 'anhquoc1',
    fullname: 'Lam Anh Quoc 1',
    gender: null,
    birthday: null,
    avatar: 'https://bic-dev-entity-attribute-s3-bucket.s3.ap-southeast-1.amazonaws.com/static/user/default-avatar.png',
    beinStaffRole: null,
    backgroundImgUrl: 'https://evolgroup.vn/wp-content/uploads/sites/18/2020/04/Thumb-EVOL.jpg',
    countryCode: null,
    phone: null,
    address: null,
    city: null,
    country: null,
    language: null,
    description: null,
    relationshipStatus: null,
    createdAt: '2022-12-12T02:58:17.853Z',
    updatedAt: '2023-01-06T08:09:51.577Z',
    deletedAt: null,
    communitiesOrder: [{ id: '51de0449-2cf8-4b9b-8d5f-d0925ef98d6e', isPinned: false }],
    latestWork: null,
  },
};

export const responseGetCity = {
  code: 'api.ok',
  meta: { message: 'Success' },
  data: [
    { name: 'An Giang', countryCode: '+84' },
    { name: 'Bà Rịa-Vũng Tàu', countryCode: '+84' },
    { name: 'Bắc Giang', countryCode: '+84' },
    { name: 'Bắc Kạn', countryCode: '+84' },
    { name: 'Bạc Liêu', countryCode: '+84' },
    { name: 'Bắc Ninh', countryCode: '+84' },
    { name: 'Bến Tre', countryCode: '+84' },
    { name: 'Bình Định', countryCode: '+84' },
    { name: 'Bình Dương', countryCode: '+84' },
    { name: 'Bình Phước', countryCode: '+84' },
    { name: 'Bình Thuận', countryCode: '+84' },
    { name: 'Cà Mau', countryCode: '+84' },
    { name: 'Cần Thơ', countryCode: '+84' },
    { name: 'Cao Bằng', countryCode: '+84' },
    { name: 'Đà Nẵng', countryCode: '+84' },
    { name: 'Đắk Lắk', countryCode: '+84' },
    { name: 'Đắk Nông', countryCode: '+84' },
    { name: 'Điện Biên', countryCode: '+84' },
    { name: 'Đồng Nai', countryCode: '+84' },
    { name: 'Đồng Tháp', countryCode: '+84' },
    { name: 'Gia Lai', countryCode: '+84' },
    { name: 'Hà Giang', countryCode: '+84' },
    { name: 'Hà Nam', countryCode: '+84' },
    { name: 'Hà Nội', countryCode: '+84' },
    { name: 'Hà Tĩnh', countryCode: '+84' },
    { name: 'Hải Dương', countryCode: '+84' },
    { name: 'Hải Phòng', countryCode: '+84' },
    { name: 'Hậu Giang', countryCode: '+84' },
    { name: 'Hồ Chí Minh', countryCode: '+84' },
    { name: 'Hòa Bình', countryCode: '+84' },
    { name: 'Hưng Yên', countryCode: '+84' },
    { name: 'Khánh Hòa', countryCode: '+84' },
    { name: 'Kiên Giang', countryCode: '+84' },
    { name: 'Kon Tum', countryCode: '+84' },
    { name: 'Lai Châu', countryCode: '+84' },
    { name: 'Lâm Đồng', countryCode: '+84' },
    { name: 'Lạng Sơn', countryCode: '+84' },
    { name: 'Lào Cai', countryCode: '+84' },
    { name: 'Long An', countryCode: '+84' },
    { name: 'Nam Định', countryCode: '+84' },
    { name: 'Nghệ An', countryCode: '+84' },
    { name: 'Ninh Bình', countryCode: '+84' },
    { name: 'Ninh Thuận', countryCode: '+84' },
    { name: 'Phú Thọ', countryCode: '+84' },
    { name: 'Phú Yên', countryCode: '+84' },
    { name: 'Quảng Bình', countryCode: '+84' },
    { name: 'Quảng Nam', countryCode: '+84' },
    { name: 'Quảng Ngãi', countryCode: '+84' },
    { name: 'Quảng Ninh', countryCode: '+84' },
    { name: 'Quảng Trị', countryCode: '+84' },
    { name: 'Sóc Trăng', countryCode: '+84' },
    { name: 'Sơn La', countryCode: '+84' },
    { name: 'Tây Ninh', countryCode: '+84' },
    { name: 'Thái Bình', countryCode: '+84' },
    { name: 'Thái Nguyên', countryCode: '+84' },
    { name: 'Thanh Hóa', countryCode: '+84' },
    { name: 'Thừa Thiên-Huế', countryCode: '+84' },
    { name: 'Tiền Giang', countryCode: '+84' },
    { name: 'Trà Vinh', countryCode: '+84' },
    { name: 'Tuyên Quang', countryCode: '+84' },
    { name: 'Vĩnh Long', countryCode: '+84' },
    { name: 'Vĩnh Phúc', countryCode: '+84' },
    { name: 'Yên Bái', countryCode: '+84' },
  ],
};

export const responseGetCountry = {
  code: 'api.ok',
  meta: { message: 'Success' },
  data: [
    {
      name: 'Việt Nam',
      flag: '🇻🇳',
      isoCode: 'VN',
      countryCode: '+84',
    },
  ],
};

export const responseGetLanguages = {
  code: 'api.ok',
  meta: { message: 'Success' },
  data: [
    { code: 'en', local: 'English' },
    { code: 'vi', local: 'Tiếng Việt' },
  ],
};

export const responseGetWorkExperience = {
  code: 'api.ok',
  meta: { message: 'Success' },
  data: [
    {
      id: '569003c7-e00b-480d-b7fa-9b1ead43c15e',
      company: 'Test',
      location: 'Bà Rịa-Vũng Tàu',
      titlePosition: 'Test',
      description: 'Test',
      currentlyWorkHere: true,
      startDate: '2023-02-12T17:00:00.000Z',
      endDate: null,
    },
  ],
};
