export default {
  SET_USER: 'auth/SET_USER',
  SET_LOADING: 'auth/SET_LOADING',
  SET_SIGNING_IN_ERROR: 'auth/SET_SIGNING_IN_ERROR',
  SET_FORGOT_PASSWORD_LOADING: 'auth/SET_FORGOT_PASSWORD_LOADING',
  SET_FORGOT_PASSWORD_STAGE: 'auth/SET_FORGOT_PASSWORD_STAGE',
  SET_FORGOT_PASSWORD_ERROR: 'auth/SET_FORGOT_PASSWORD_ERROR',
  SET_CHANGE_PASSWORD_ERROR: 'auth/SET_CHANGE_PASSWORD_ERROR',
  SET_CHANGE_PASSWORD_LOADING: 'auth/SET_CHANGE_PASSWORD_LOADING',

  SIGN_IN: 'auth/SIGN_IN',
  SIGN_UP: 'auth/SIGN_UP',
  SIGN_OUT: 'auth/SIGN_OUT',
  FORGOT_PASSWORD_REQUEST: 'auth/FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_CONFIRM: 'auth/FORGOT_PASSWORD_CONFIRM',
  SIGN_IN_SUCCESS: 'auth/SIGN_IN_SUCCESS',
  CHANGE_PASSWORD: 'auth/CHANGE_PASSWORD',
};
