export const CURRENT_SERVER = 'https://chat.beincomm.com';

export const ExperimentalNormalizeMarkdownLinks = false;

export const CODE_FONT_FAMILY = 'JetBrainsMono-Regular';

export const DeepLinkTypes = {
  CHANNEL: 'channel',
  DMCHANNEL: 'dmchannel',
  GROUPCHANNEL: 'groupchannel',
  PERMALINK: 'permalink',
  OTHER: 'other',
  PLUGIN: 'plugin',
};

export const mmConfig = {};

export const languages = {
  actionscript: 'ActionScript',
  applescript: 'AppleScript',
  bash: 'Bash',
  clojure: 'Clojure',
  coffeescript: 'CoffeeScript',
  cpp: 'C++',
  cs: 'C#',
  css: 'CSS',
  d: 'D',
  dart: 'Dart',
  delphi: 'Delphi',
  diff: 'Diff',
  django: 'Django',
  dockerfile: 'Dockerfile',
  elixir: 'Elixir',
  erlang: 'Erlang',
  fortran: 'Fortran',
  fsharp: 'F#',
  gcode: 'G-code',
  go: 'Go',
  groovy: 'Groovy',
  handlebars: 'Handlebars',
  haskell: 'Haskell',
  haxe: 'Haxe',
  html: 'HTML',
  java: 'Java',
  javascript: 'JavaScript',
  json: 'JSON',
  julia: 'Julia',
  kotlin: 'Kotlin',
  latex: 'LaTeX',
  less: 'Less',
  lisp: 'Lisp',
  lua: 'Lua',
  makefile: 'Makefile',
  markdown: 'Markdown',
  matlab: 'Matlab',
  objectivec: 'Objective-C',
  ocaml: 'OCaml',
  perl: 'Perl',
  php: 'PHP',
  powershell: 'PowerShell',
  puppet: 'Puppet',
  python: 'Python',
  r: 'R',
  ruby: 'Ruby',
  rust: 'Rust',
  scala: 'Scala',
  scheme: 'Scheme',
  scss: 'SCSS',
  smalltalk: 'Smalltalk',
  sql: 'SQL',
  swift: 'Swift',
  tex: 'TeX',
  vbnet: 'VB.NET',
  vbscript: 'VBScript',
  verilog: 'Verilog',
  xml: 'XML',
  yaml: 'YAML',
};

export const Files = {
  AUDIO_TYPES: ['mp3', 'wav', 'wma', 'm4a', 'flac', 'aac', 'ogg'],
  CODE_TYPES: [
    'as',
    'applescript',
    'osascript',
    'scpt',
    'bash',
    'sh',
    'zsh',
    'clj',
    'boot',
    'cl2',
    'cljc',
    'cljs',
    'cljs.hl',
    'cljscm',
    'cljx',
    'hic',
    'coffee',
    '_coffee',
    'cake',
    'cjsx',
    'cson',
    'iced',
    'cpp',
    'c',
    'cc',
    'h',
    'c++',
    'h++',
    'hpp',
    'cs',
    'csharp',
    'css',
    'd',
    'di',
    'dart',
    'delphi',
    'dpr',
    'dfm',
    'pas',
    'pascal',
    'freepascal',
    'lazarus',
    'lpr',
    'lfm',
    'diff',
    'django',
    'jinja',
    'dockerfile',
    'docker',
    'erl',
    'f90',
    'f95',
    'fsharp',
    'fs',
    'gcode',
    'nc',
    'go',
    'groovy',
    'handlebars',
    'hbs',
    'html.hbs',
    'html.handlebars',
    'hs',
    'hx',
    'java',
    'jsp',
    'js',
    'jsx',
    'json',
    'jl',
    'kt',
    'ktm',
    'kts',
    'less',
    'lisp',
    'lua',
    'mk',
    'mak',
    'md',
    'mkdown',
    'mkd',
    'matlab',
    'm',
    'mm',
    'objc',
    'obj-c',
    'ml',
    'perl',
    'pl',
    'php',
    'php3',
    'php4',
    'php5',
    'php6',
    'ps',
    'ps1',
    'pp',
    'py',
    'gyp',
    'r',
    'ruby',
    'rb',
    'gemspec',
    'podspec',
    'thor',
    'irb',
    'rs',
    'scala',
    'scm',
    'sld',
    'scss',
    'st',
    'sql',
    'swift',
    'tex',
    'vbnet',
    'vb',
    'bas',
    'vbs',
    'v',
    'veo',
    'xml',
    'html',
    'xhtml',
    'rss',
    'atom',
    'xsl',
    'plist',
    'yaml',
  ],
  IMAGE_TYPES: ['jpg', 'gif', 'bmp', 'png', 'jpeg', 'tiff', 'tif'],
  PATCH_TYPES: ['patch'],
  PDF_TYPES: ['pdf'],
  PRESENTATION_TYPES: ['ppt', 'pptx'],
  SPREADSHEET_TYPES: ['xlsx', 'csv'],
  TEXT_TYPES: ['txt', 'rtf'],
  VIDEO_TYPES: ['mp4', 'avi', 'webm', 'mkv', 'wmv', 'mpg', 'mov', 'flv'],
  WORD_TYPES: ['doc', 'docx'],
  ZIP_TYPES: ['zip'],
};
