const postTypes = {
  SET_LOADING_CREATE_POST: '/post/SET_LOADING_CREATE_POST',
  CLEAR_CREATE_POST_DATA: '/post/CLEAR_CREATE_POST_DATA',
  SET_CREATE_POST_DATA: 'post/SET_CREATE_POST_DATA',
  SET_CREATE_POST_AUDIENCE: 'post/SET_CREATE_POST_AUDIENCE',
  SET_CREATE_POST_TAGS: 'post/SET_CREATE_POST_TAGS',

  //saga
  POST_CREATE_NEW_POST: '/post/POST_CREATE_NEW_POST',
};

export default postTypes;
