const postTypes = {
  //create post
  SET_LOADING_CREATE_POST: '/post/SET_LOADING_CREATE_POST',
  CLEAR_CREATE_POST: '/post/CLEAR_CREATE_POST',
  SET_CREATE_POST_DATA: 'post/SET_CREATE_POST_DATA',
  SET_CREATE_POST_CHOSEN_AUDIENCES: 'post/SET_CREATE_POST_CHOSEN_AUDIENCES',
  SET_CREATE_POST_IMPORTANT: 'post/SET_CREATE_POST_IMPORTANT',
  //create post select audiences
  SET_SEARCH_RESULT_AUDIENCE_GROUPS: 'post/SET_SEARCH_RESULT_AUDIENCE_GROUPS',
  SET_SEARCH_RESULT_AUDIENCE_USERS: 'post/SET_SEARCH_RESULT_AUDIENCE_USERS',
  //post detail
  SET_POST_DETAIL: 'post/SET_POST_DETAIL',
  SET_POST_DETAIL_REPLYING_COMMENT: 'post/SET_POST_DETAIL_REPLYING_COMMENT',
  //mention
  SET_MENTION_SEARCH_KEY: 'post/SET_MENTION_SEARCH_KEY',
  SET_MENTION_SEARCH_RESULT: 'post/SET_MENTION_SEARCH_RESULT',

  //saga
  POST_CREATE_NEW_POST: '/post/POST_CREATE_NEW_POST',
  GET_SEARCH_MENTION_AUDIENCES: 'post/GET_SEARCH_MENTION_AUDIENCES',
};

export default postTypes;
