version: 2.1

orbs:
  android: circleci/android@2.0.3
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  sonarcloud-scan:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Install NPM
          command: npm install --legacy-peer-deps
      - sonarcloud/scan
  ios-stg-update:
    macos:
      xcode: 14.2.0
    resource_class: medium #medium|large
    steps:
      - checkout
      - run:
          name: Import environment variables from Doppler
          command: |
             echo -e $STG_ENV > .env.staging
             echo APP_VERSION=${STG_APP_VERSION} >> .env.staging
             echo UPDATE_DESC=${STG_UPDATE_DESC} >> .env.staging
             echo REMOTE_CONFIG_CACHE_TIME=${STG_REMOTE_CONFIG_CACHE_TIME} >> .env.staging
             echo NOTICE_WEBHOOK=${NOTICE_WEBHOOK} >> .env.staging
             echo -e $STG_FASTLANE_ENV > fastlane/.env
      - run:
          name: Install NPM
          command: npm install --legacy-peer-deps
      - run:
          name: Install AppCenter CLI
          command: npm install -g appcenter-cli
      - run:
          name: Install Bundle
          command: bundle install
      - run:
          name: CodePush update iOS Staging
          command: bundle exec fastlane ios update_staging

  ios-pre-update:
    macos:
      xcode: 14.2.0
    resource_class: medium #medium|large
    steps:
      - checkout
      - run:
          name: Import environment variables from Doppler
          command: |
            echo -e $REL_ENV > .env.prerelease
            echo APP_VERSION=${REL_APP_VERSION} >> .env.prerelease
            echo UPDATE_DESC=${REL_UPDATE_DESC} >> .env.prerelease
            echo REMOTE_CONFIG_CACHE_TIME=${REL_REMOTE_CONFIG_CACHE_TIME} >> .env.prerelease
            echo NOTICE_WEBHOOK=${NOTICE_WEBHOOK} >> .env.prerelease
            echo -e $REL_FASTLANE_ENV > fastlane/.env
      - run:
          name: Install NPM
          command: npm install --legacy-peer-deps
      - run:
          name: Install AppCenter CLI
          command: npm install -g appcenter-cli
      - run:
          name: Install Bundle
          command: bundle install
      - run:
          name: CodePush update iOS PreRelease
          command: bundle exec fastlane ios update_prerelease

  ios-pro-update:
    macos:
      xcode: 14.2.0
    resource_class: medium #medium|large
    steps:
      - checkout
      - run:
          name: Import environment variables from Doppler
          command: |
              echo -e $PRO_ENV > .env.production
              echo APP_VERSION=${PRO_APP_VERSION} >> .env.production
              echo UPDATE_DESC=${PRO_UPDATE_DESC} >> .env.production
              echo REMOTE_CONFIG_CACHE_TIME=${PRO_REMOTE_CONFIG_CACHE_TIME} >> .env.production
              echo NOTICE_WEBHOOK=${NOTICE_WEBHOOK} >> .env.production
              echo -e $PRO_FASTLANE_ENV > fastlane/.env
      - run:
          name: Install NPM
          command: npm install --legacy-peer-deps
      - run:
          name: Install AppCenter CLI
          command: npm install -g appcenter-cli
      - run:
          name: Install Bundle
          command: bundle install
      - run:
          name: CodePush update iOS Production
          command: bundle exec fastlane ios update_production

  ios-stg:
    macos:
      xcode: 14.2.0
    resource_class: medium #medium|large
    steps:
      - checkout
      - run:
          name: Import environment variables from Doppler
          command: |
            echo -e $STG_ENV > .env.staging
            echo APP_VERSION=${STG_APP_VERSION} >> .env.staging
            echo UPDATE_DESC=${STG_UPDATE_DESC} >> .env.staging
            echo REMOTE_CONFIG_CACHE_TIME=${STG_REMOTE_CONFIG_CACHE_TIME} >> .env.staging
            echo NOTICE_WEBHOOK=${NOTICE_WEBHOOK} >> .env.staging
            echo -e $STG_FASTLANE_ENV > fastlane/.env
            echo $API_KEY | base64 --decode >  fastlane/api_key_info.json
            echo $STG_GOOGLE_SERVICES_PLIST_IOS | base64 --decode > ios/Firebase/GoogleService-Info-Staging.plist
      - run:
          name: Install NPM
          command: npm install --legacy-peer-deps
      - run:
          name: Install AppCenter CLI
          command: npm install -g appcenter-cli
      - run:
          name: Install Bundle
          command: bundle install
      - run:
          name: Install Cocoapods
          command: cd ios && sudo gem install cocoapods
      - run:
          name: Install Pod
          command: cd ios && pod install
      - run:
          name: Fastlane Build, Deploy to TestFlight and Update CodePush
          command: bundle exec fastlane ios $STG_FASTLANE_LANE_IOS

  ios-pre:
    macos:
      xcode: 14.2.0
    resource_class: medium #medium|large
    steps:
      - checkout
      - run:
          name: Import environment variables from Doppler
          command: |
            echo -e $REL_ENV > .env.prerelease
            echo APP_VERSION=${REL_APP_VERSION} >> .env.prerelease
            echo UPDATE_DESC=${REL_UPDATE_DESC} >> .env.prerelease
            echo REMOTE_CONFIG_CACHE_TIME=${REL_REMOTE_CONFIG_CACHE_TIME} >> .env.prerelease
            echo NOTICE_WEBHOOK=${NOTICE_WEBHOOK} >> .env.prerelease
            echo -e $REL_FASTLANE_ENV > fastlane/.env
            echo $API_KEY | base64 --decode >  fastlane/api_key_info.json
            echo $REL_GOOGLE_SERVICES_PLIST_IOS | base64 --decode > ios/Firebase/GoogleService-Info-Prerelease.plist
      - run:
          name: Install NPM
          command: npm install --legacy-peer-deps
      - run:
          name: Install AppCenter CLI
          command: npm install -g appcenter-cli
      - run:
          name: Install Bundle
          command: bundle install
      - run:
          name: Install Cocoapods
          command: cd ios && sudo gem install cocoapods
      - run:
          name: Install Pod
          command: cd ios && pod install
      - run:
          name: Fastlane Build, Deploy to TestFlight and Update CodePush
          command: bundle exec fastlane ios $REL_FASTLANE_LANE_IOS


  ios-pro:
    macos:
      xcode: 14.2.0
    resource_class: medium #medium|large
    steps:
      - checkout
      - run:
          name: Import environment variables from Doppler
          command: |
            echo -e $PRO_ENV > .env.production
            echo APP_VERSION=${PRO_APP_VERSION} >> .env.production
            echo UPDATE_DESC=${PRO_UPDATE_DESC} >> .env.production
            echo REMOTE_CONFIG_CACHE_TIME=${PRO_REMOTE_CONFIG_CACHE_TIME} >> .env.production
            echo NOTICE_WEBHOOK=${NOTICE_WEBHOOK} >> .env.production
            echo -e $PRO_FASTLANE_ENV > fastlane/.env
            echo $API_KEY | base64 --decode >  fastlane/api_key_info.json
            echo $PRO_GOOGLE_SERVICES_PLIST_IOS | base64 --decode > ios/Firebase/GoogleService-Info-Production.plist
      - run:
          name: Install NPM
          command: npm install --legacy-peer-deps
      - run:
          name: Install AppCenter CLI
          command: npm install -g appcenter-cli
      - run:
          name: Install Bundle
          command: bundle install
      - run:
          name: Install Cocoapods
          command: cd ios && sudo gem install cocoapods
      - run:
          name: Install Pod
          command: cd ios && pod install
      - run:
          name: Fastlane Build, Deploy to TestFlight and Update CodePush
          command: bundle exec fastlane ios $PRO_FASTLANE_LANE_IOS
      - store_artifacts:
          path: output

  android-stg-update:
    executor:
      name: android/android-machine
      tag: 2022.03.1
    steps:
      - checkout
      - run:
          name: Import environment variables from Doppler
          command: |
              echo -e $STG_ENV > .env.staging
              echo APP_VERSION=${STG_APP_VERSION} >> .env.staging
              echo UPDATE_DESC=${STG_UPDATE_DESC} >> .env.staging
              echo REMOTE_CONFIG_CACHE_TIME=${STG_REMOTE_CONFIG_CACHE_TIME} >> .env.staging
              echo NOTICE_WEBHOOK=${NOTICE_WEBHOOK} >> .env.staging
              echo -e $STG_FASTLANE_ENV > fastlane/.env
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: Install AppCenter CLI
          command: npm install -g appcenter-cli
      - run:
          name: Install Bundle
          command: bundle install
      - run:
          name: CodePush update Android Staging
          command: bundle exec fastlane android update_staging

  android-pre-update:
    executor:
      name: android/android-machine
      tag: 2022.03.1
    steps:
      - checkout
      - run:
          name: Import environment variables from Doppler
          command: |
            echo -e $REL_ENV > .env.prerelease
            echo APP_VERSION=${REL_APP_VERSION} >> .env.prerelease
            echo UPDATE_DESC=${REL_UPDATE_DESC} >> .env.prerelease
            echo REMOTE_CONFIG_CACHE_TIME=${REL_REMOTE_CONFIG_CACHE_TIME} >> .env.prerelease
            echo NOTICE_WEBHOOK=${NOTICE_WEBHOOK} >> .env.prerelease
            echo -e $REL_FASTLANE_ENV > fastlane/.env
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: Install AppCenter CLI
          command: npm install -g appcenter-cli
      - run:
          name: Install Bundle
          command: bundle install
      - run:
          name: CodePush update Android PreRelease
          command: bundle exec fastlane android update_prerelease

  android-pro-update:
    executor:
      name: android/android-machine
      tag: 2022.03.1
    steps:
      - checkout
      - run:
          name: Import environment variables from Doppler
          command: |
              echo -e $PRO_ENV > .env.production
              echo APP_VERSION=${PRO_APP_VERSION} >> .env.production
              echo UPDATE_DESC=${PRO_UPDATE_DESC} >> .env.production
              echo REMOTE_CONFIG_CACHE_TIME=${PRO_REMOTE_CONFIG_CACHE_TIME} >> .env.production
              echo NOTICE_WEBHOOK=${NOTICE_WEBHOOK} >> .env.production
              echo -e $PRO_FASTLANE_ENV > fastlane/.env
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: Install AppCenter CLI
          command: npm install -g appcenter-cli
      - run:
          name: Install Bundle
          command: bundle install
      - run:
          name: CodePush update Android Production
          command: bundle exec fastlane android update_production

  android-stg:
    executor:
      name: android/android-machine
      tag: 2022.03.1
    steps:
      - checkout
      - run:
          name: Import environment variables from Doppler
          command: |
            echo -e $STG_ENV > .env.staging
            echo APP_VERSION=${STG_APP_VERSION} >> .env.staging
            echo UPDATE_DESC=${STG_UPDATE_DESC} >> .env.staging
            echo REMOTE_CONFIG_CACHE_TIME=${STG_REMOTE_CONFIG_CACHE_TIME} >> .env.staging
            echo NOTICE_WEBHOOK=${NOTICE_WEBHOOK} >> .env.staging
            echo -e $STG_FASTLANE_ENV > fastlane/.env
            mkdir -p android/app/src/staging
            echo $STG_GOOGLE_SERVICES_JSON_ANDROID | base64 --decode > android/app/src/staging/google-services.json
      - run:
          name: Pull Keystore from AWS S3 bucket
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            sudo unzip awscliv2.zip
            sudo ./aws/install
            aws --version
            export AWS_ACCESS_KEY_ID=$STG_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$STG_AWS_SECRET_ACCESS_KEY
            aws s3 cp s3://$STG_S3_BUCKET/group-app/staging.keystore android/app/
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: Install AppCenter CLI
          command: npm install -g appcenter-cli
      - run:
          name: Install Bundle
          command: bundle install
      - run:
          name: Fastlane Build, Deploy to App Distribution and Update CodePush
          command: bundle exec fastlane android $STG_FASTLANE_LANE_ANDROID
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release-unsigned.apk

  android-pre:
    executor:
      name: android/android-machine
      tag: 2022.03.1
    steps:
      - checkout
      - run:
          name: Import environment variables from Doppler
          command: |
            echo -e $REL_ENV > .env.prerelease
            echo APP_VERSION=${REL_APP_VERSION} >> .env.prerelease
            echo UPDATE_DESC=${REL_UPDATE_DESC} >> .env.prerelease
            echo REMOTE_CONFIG_CACHE_TIME=${REL_REMOTE_CONFIG_CACHE_TIME} >> .env.prerelease
            echo NOTICE_WEBHOOK=${NOTICE_WEBHOOK} >> .env.prerelease
            echo -e $REL_FASTLANE_ENV > fastlane/.env
            mkdir -p android/app/src/prerelease
            echo $REL_GOOGLE_SERVICES_JSON_ANDROID | base64 --decode > android/app/src/prerelease/google-services.json
      - run:
          name: Pull Keystore from AWS S3 bucket
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            sudo unzip awscliv2.zip
            sudo ./aws/install
            aws --version
            export AWS_ACCESS_KEY_ID=$REL_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$REL_AWS_SECRET_ACCESS_KEY
            aws s3 cp s3://$REL_S3_BUCKET/group-app/prerelease.keystore android/app/
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: Install AppCenter CLI
          command: npm install -g appcenter-cli
      - run:
          name: Install Bundle
          command: bundle install
      - run:
          name: Fastlane Build, Deploy to App Distribution and Update CodePush
          command: bundle exec fastlane android $REL_FASTLANE_LANE_ANDROID

  android-pro:
    executor:
      name: android/android-machine
      tag: 2022.03.1
    steps:
      - checkout
      - run:
          name: Import environment variables from Doppler
          command: |
            echo -e $PRO_ENV > .env.production
            echo APP_VERSION=${PRO_APP_VERSION} >> .env.production
            echo UPDATE_DESC=${PRO_UPDATE_DESC} >> .env.production
            echo REMOTE_CONFIG_CACHE_TIME=${PRO_REMOTE_CONFIG_CACHE_TIME} >> .env.production
            echo NOTICE_WEBHOOK=${NOTICE_WEBHOOK} >> .env.production
            echo -e $PRO_FASTLANE_ENV > fastlane/.env
            mkdir -p a android/app/src/production
            echo $PRO_GOOGLE_SERVICES_JSON_ANDROID | base64 --decode > android/app/src/production/google-services.json
      - run:
          name: Pull Keystore from AWS S3 bucket
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            sudo unzip awscliv2.zip
            sudo ./aws/install
            aws --version
            export AWS_ACCESS_KEY_ID=$PRO_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$PRO_AWS_SECRET_ACCESS_KEY
            aws s3 cp s3://$PRO_S3_BUCKET/group-app/production.keystore android/app/
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: Install AppCenter CLI
          command: npm install -g appcenter-cli
      - run:
          name: Install Bundle
          command: bundle install
      - run:
          name: Fastlane Build, Deploy to App Distribution and Update CodePush
          command: bundle exec fastlane android $PRO_FASTLANE_LANE_ANDROID
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release-unsigned.apk

workflows:
  version: 2
  Develop:
    jobs:
      - sonarcloud-scan:
          filters:
            branches:
              only: /^BEIN.*$/

  Staging:
    jobs:
      - sonarcloud-scan:
          filters:
            branches:
              only: /^staging.*$/

      - ios-stg-update-approval:
          filters:
            branches:
              only: /^staging.*$/
          type: approval
      - android-stg-update-approval:
          filters:
            branches:
              only: /^staging.*$/
          type: approval
      - ios-stg-update:
          filters:
            branches:
              only: /^staging.*$/
          requires:
            - ios-stg-update-approval
      - android-stg-update:
          filters:
            branches:
              only: /^staging.*$/
          requires:
            - android-stg-update-approval

      - ios-approval:
          filters:
            branches:
              only: /^staging.*$/
          type: approval
      - android-approval:
          filters:
            branches:
              only: /^staging.*$/
          type: approval
      - ios-stg:
          filters:
            branches:
              only: /^staging.*$/
          requires:
            - ios-approval
      - android-stg:
          filters:
            branches:
              only: /^staging.*$/
          requires:
            - android-approval

  PreRelease:
    jobs:
      - sonarcloud-scan:
          filters:
            branches:
              only: /^release.*$/

      - ios-pre-update-approval:
          filters:
            branches:
              only: /^release.*$/
          type: approval
      - android-pre-update-approval:
          filters:
            branches:
              only: /^release.*$/
          type: approval
      - ios-pre-update:
          filters:
            branches:
              only: /^release.*$/
          requires:
            - ios-pre-update-approval
      - android-pre-update:
          filters:
            branches:
              only: /^release.*$/
          requires:
            - android-pre-update-approval

      - ios-pre-approval:
          filters:
            branches:
              only: /^release.*$/
          type: approval
      - android-pre-approval:
          filters:
            branches:
              only: /^release.*$/
          type: approval
      - ios-pre:
          filters:
            branches:
              only: /^release.*$/
          requires:
            - ios-pre-approval
      - android-pre:
          filters:
            branches:
              only: /^release.*$/
          requires:
            - android-pre-approval

  Production:
    jobs:
      - sonarcloud-scan:
          filters:
            branches:
              only: ^master.*$/

      - ios-pro-update-approval:
          filters:
            branches:
              only: /^master.*$/
          type: approval
      - android-pro-update-approval:
          filters:
            branches:
              only: ^master.*$/
          type: approval
      - ios-pro-update:
          filters:
            branches:
              only: ^master.*$/
          requires:
            - ios-pro-update-approval
      - android-pro-update:
          filters:
            branches:
              only: ^master.*$/
          requires:
            - android-pro-update-approval

      - ios-approval:
          filters:
            branches:
              only: ^master.*$/
          type: approval
      - android-approval:
          filters:
            branches:
              only: ^master.*$/
          type: approval
      - ios-pro:
          filters:
            branches:
              only: ^master.*$/
          requires:
            - ios-approval
      - android-pro:
          filters:
            branches:
              only: ^master.*$/
          requires:
            - android-approval
