version: 2.1

orbs:
  android: circleci/android@2.0.3

jobs:
  ios-stg:
    macos:
      xcode: 13.4.1
    resource_class: medium #medium|large
    steps:
      - checkout
      - run:
          name: Import environment variables from Doppler
          command: |
            echo -e $STG_ENV > .env.staging
            echo APP_VERSION=${APP_VERSION} >> .env.staging
            echo -e $STG_FASTLANE_ENV > ios/fastlane/.env
            echo $API_KEY | base64 --decode >  ios/fastlane/api_key_info.json
            echo $STG_GOOGLE_SERVICES_PLIST_IOS | base64 --decode > ios/Firebase/GoogleService-Info-Staging.plist
      - run:
          name: Install NPM
          command: npm install --legacy-peer-deps
      - run:
          name: Install Bundle
          command: cd ios && bundle install
      - run:
          name: Install Cocoapods
          command: cd ios && sudo gem install cocoapods
      - run:
          name: Install Pod
          command: cd ios && pod install
      - run:
          name: Fastlane build and deploy TestFlight
          command: cd ios && bundle exec fastlane $STG_FASTLANE_LANE_IOS
      - store_artifacts:
          path: output

  ios-pro: 
    macos:
      xcode: 13.4.1
    resource_class: medium #medium|large
    steps:
      - checkout
      - run:
          name: Import environment variables from Doppler
          command: |
            echo -e $PRO_ENV > .env.production
            echo APP_VERSION=${APP_VERSION} >> .env.production
            echo -e $PRO_FASTLANE_ENV > ios/fastlane/.env
            echo $API_KEY | base64 --decode >  ios/fastlane/api_key_info.json
            echo $PRO_GOOGLE_SERVICES_PLIST_IOS | base64 --decode > ios/Firebase/GoogleService-Info-Production.plist
      - run:
          name: Install NPM
          command: npm install --legacy-peer-deps
      - run:
          name: Install Bundle
          command: cd ios && bundle install
      - run:
          name: Install Cocoapods
          command: cd ios && sudo gem install cocoapods
      - run:
          name: Install Pod
          command: cd ios && pod install
      - run:
          name: Fastlane build and deploy TestFlight
          command: cd ios && bundle exec fastlane $PRO_FASTLANE_LANE_IOS
      - store_artifacts:
          path: output

  android-stg:
    executor:
      name: android/android-machine
      tag: 2022.03.1
    steps:
      - checkout
      - run:
          name: Import environment variables from Doppler
          command: |
            echo -e $STG_ENV > .env.staging
            mkdir -p android/app/src/staging
            echo $STG_GOOGLE_SERVICES_JSON_ANDROID | base64 --decode > android/app/src/staging/google-services.json
      - run:
          name: Pull Keystore from AWS S3 bucket
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            sudo unzip awscliv2.zip
            sudo ./aws/install
            aws --version
            export AWS_ACCESS_KEY_ID=$STG_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$STG_AWS_SECRET_ACCESS_KEY
            aws s3 cp s3://$STG_S3_BUCKET/group-app/staging.keystore android/app/
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: Install Bundle
          command: cd android && bundle install
      - run:
          name: Fastlane build and deploy Diawi
          command: cd android && bundle exec fastlane $STG_FASTLANE_LANE_ANDROID
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release-unsigned.apk

  android-pro:
    executor:
      name: android/android-machine
      tag: 2022.03.1
    steps:
      - checkout
      - run:
          name: Import environment variables from Doppler
          command: |
            echo -e $PRO_ENV > .env.production
            mkdir -p a android/app/src/production
            echo $PRO_GOOGLE_SERVICES_JSON_ANDROID | base64 --decode > android/app/src/production/google-services.json
      - run:
          name: Pull Keystore from AWS S3 bucket
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            sudo unzip awscliv2.zip
            sudo ./aws/install
            aws --version
            export AWS_ACCESS_KEY_ID=$PRO_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$PRO_AWS_SECRET_ACCESS_KEY
            aws s3 cp s3://$PRO_S3_BUCKET/group-app/production.keystore android/app/
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: Install Bundle
          command: cd android && bundle install
      - run:
          name: Fastlane Build and Deploy to Diawi
          command: cd android && bundle exec fastlane $PRO_FASTLANE_LANE_ANDROID
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release-unsigned.apk

workflows:
  version: 2
  Staging_iOS-Android:
    jobs:
      - iOS-Approval:
          type: approval
      - Android-Approval:
          type: approval
      - ios-stg:
          filters:
            branches:
              only: /^staging.*$/
          requires:
            - iOS-Approval
      - android-stg:
          filters:
            branches:
              only: /^staging.*$/
          requires:
            - Android-Approval

  Production_iOS-Android:
    jobs:
      - ios-pro:
          filters:
            branches:
              only: /^master.*$/
      - android-pro:
          filters:
            branches:
              only: /^master.*$/
