version: 2.1

orbs:
  android: circleci/android@1.0.3
  gcp-cli: circleci/gcp-cli@2.2.0

jobs:
  ios-stg:
    macos:
      xcode: 13.4.1
    environment:
      FL_OUTPUT_DIR: ./fastlane/staging/
      FASTLANE_LANE: deploy_staging_ci
    steps:
      - checkout
      - run:
          name: Import environment variables from Contexts
          command: |
            cat >.env.staging \<<EOL
            SELF_DOMAIN=${SELF_DOMAIN}
            CHAT_DOMAIN=${CHAT_DOMAIN}
            BEIN_FEED=${BEIN_FEED}
            BEIN_FEED_VERSION=${BEIN_FEED_VERSION}
            BEIN_FEED_WS_MSGPACK=${BEIN_FEED_WS_MSGPACK}
            BEIN_API=${BEIN_API}
            BEIN_NOTIFICATION=${BEIN_NOTIFICATION}
            BEIN_UPLOAD=${BEIN_UPLOAD}
            BEIN_RESOURCE=${BEIN_RESOURCE}
            BEIN_AWS_PROJECT_REGION=${BEIN_AWS_PROJECT_REGION}
            BEIN_AWS_COGNITO_REGION=${BEIN_AWS_COGNITO_REGION}
            BEIN_AWS_USER_POOLS_ID=${BEIN_AWS_USER_POOLS_ID}
            BEIN_AWS_USER_POOLS_WEB_CLIENT_ID=${BEIN_AWS_USER_POOLS_WEB_CLIENT_ID}
            BEIN_CHAT_DEEPLINK=${BEIN_CHAT_DEEPLINK}
            BEIN_CHAT_SOCKET=${BEIN_CHAT_SOCKET}
            APP_VERSION=${APP_VERSION}
            APP_GROUP_PACKAGE_NAME_IOS=${APP_GROUP_PACKAGE_NAME_IOS}
            APP_GROUP_PACKAGE_NAME_ANDROID=${APP_GROUP_PACKAGE_NAME_ANDROID}
            SCHEME_NAME_IOS=${SCHEME_NAME_IOS}
            EOL
      - run:
          name: Decode the GoogleService-Info-Staging.plist from Contexts
          command: echo $GOOGLE_SERVICES_iOS | base64 --decode > ios/Firebase/GoogleService-Info-Staging.plist
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: Install Bundle
          command: cd ios && bundle install
      - run:
          name: Install Cocoapods
          command: cd ios && sudo gem install cocoapods
      - run:
          name: Install Pod
          command: cd ios && pod install
      - add_ssh_keys:
          fingerprints:
            - "9d:69:e6:39:9b:39:b6:dd:9b:50:6c:6d:b8:fd:54:26"
            - "c2:82:e5:3f:3b:bf:32:02:ab:0b:08:1d:ff:bc:ec:75"
            - "00:1c:a5:d9:5b:4c:15:02:55:4a:bf:24:22:ea:2e:35"
      - run:
          name: Fastlane build and deploy TestFlight
          command: cd ios && bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

  ios-pro:
    macos:
      xcode: 13.4.1
    environment:
      FL_OUTPUT_DIR: ./fastlane/production/
      FASTLANE_LANE: deploy_production_ci
    steps:
      - checkout
      - run:
          name: Import environment variables from Contexts
          command: |
            cat >.env.production \<<EOL
            SELF_DOMAIN=${SELF_DOMAIN}
            CHAT_DOMAIN=${CHAT_DOMAIN}
            BEIN_FEED=${BEIN_FEED}
            BEIN_FEED_VERSION=${BEIN_FEED_VERSION}
            BEIN_FEED_WS_MSGPACK=${BEIN_FEED_WS_MSGPACK}
            BEIN_API=${BEIN_API}
            BEIN_NOTIFICATION=${BEIN_NOTIFICATION}
            BEIN_UPLOAD=${BEIN_UPLOAD}
            BEIN_RESOURCE=${BEIN_RESOURCE}
            BEIN_AWS_PROJECT_REGION=${BEIN_AWS_PROJECT_REGION}
            BEIN_AWS_COGNITO_REGION=${BEIN_AWS_COGNITO_REGION}
            BEIN_AWS_USER_POOLS_ID=${BEIN_AWS_USER_POOLS_ID}
            BEIN_AWS_USER_POOLS_WEB_CLIENT_ID=${BEIN_AWS_USER_POOLS_WEB_CLIENT_ID}
            BEIN_CHAT_DEEPLINK=${BEIN_CHAT_DEEPLINK}
            BEIN_CHAT_SOCKET=${BEIN_CHAT_SOCKET}
            APP_VERSION=${APP_VERSION}
            APP_GROUP_PACKAGE_NAME_IOS=${APP_GROUP_PACKAGE_NAME_IOS}
            APP_GROUP_PACKAGE_NAME_ANDROID=${APP_GROUP_PACKAGE_NAME_ANDROID}
            SCHEME_NAME_IOS=${SCHEME_NAME_IOS}
            EOL
      - run:
          name: Decode the GoogleService-Info-Production.plist from Contexts
          command: echo $GOOGLE_SERVICES_iOS | base64 --decode > ios/Firebase/GoogleService-Info-Production.plist
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: Install Bundle
          command: cd ios && bundle install
      - run:
          name: Install Cocoapods
          command: cd ios && sudo gem install cocoapods
      - run:
          name: Install Pod
          command: cd ios && pod install
      - run:
          name: Fastlane build and deploy TestFlight
          command: cd ios && bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

  android-stg:
    executor:
      name: android/android-machine
    environment:
      FASTLANE_LANE: deploy_staging
    steps:
      - checkout
      - run:
          name: Import environment variables from Contexts into .env.staging
          command: |
            cat >.env.staging \<<EOL
            SELF_DOMAIN=${SELF_DOMAIN}
            CHAT_DOMAIN=${CHAT_DOMAIN}
            BEIN_FEED=${BEIN_FEED}
            BEIN_FEED_VERSION=${BEIN_FEED_VERSION}
            BEIN_FEED_WS_MSGPACK=${BEIN_FEED_WS_MSGPACK}
            BEIN_API=${BEIN_API}
            BEIN_NOTIFICATION=${BEIN_NOTIFICATION}
            BEIN_UPLOAD=${BEIN_UPLOAD}
            BEIN_RESOURCE=${BEIN_RESOURCE}
            BEIN_AWS_PROJECT_REGION=${BEIN_AWS_PROJECT_REGION}
            BEIN_AWS_COGNITO_REGION=${BEIN_AWS_COGNITO_REGION}
            BEIN_AWS_USER_POOLS_ID=${BEIN_AWS_USER_POOLS_ID}
            BEIN_AWS_USER_POOLS_WEB_CLIENT_ID=${BEIN_AWS_USER_POOLS_WEB_CLIENT_ID}
            BEIN_CHAT_DEEPLINK=${BEIN_CHAT_DEEPLINK}
            BEIN_CHAT_SOCKET=${BEIN_CHAT_SOCKET}
            APP_VERSION=${APP_VERSION}
            APP_GROUP_PACKAGE_NAME_IOS=${APP_GROUP_PACKAGE_NAME_IOS}
            APP_GROUP_PACKAGE_NAME_ANDROID=${APP_GROUP_PACKAGE_NAME_ANDROID}
            SCHEME_NAME_IOS=${SCHEME_NAME_IOS}
            EOL
      - run:
          name: Decode the google-services.json from Contexts
          command: echo $GOOGLE_SERVICES_Android | base64 --decode > android/app/google-services.json
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: Install Bundle
          command: cd android && bundle install
      - run:
          name: Fastlane build and deploy Diawi
          command: cd android && bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release-unsigned.apk

  android-pro:
    executor:
      name: android/android-machine
    environment:
      FASTLANE_LANE: deploy_production
    steps:
      - checkout
      - run:
          name: Import environment variables from Contexts into .env.production
          command: |
            cat >.env.production \<<EOL
            SELF_DOMAIN=${SELF_DOMAIN}
            CHAT_DOMAIN=${CHAT_DOMAIN}
            BEIN_FEED=${BEIN_FEED}
            BEIN_FEED_VERSION=${BEIN_FEED_VERSION}
            BEIN_FEED_WS_MSGPACK=${BEIN_FEED_WS_MSGPACK}
            BEIN_API=${BEIN_API}
            BEIN_NOTIFICATION=${BEIN_NOTIFICATION}
            BEIN_UPLOAD=${BEIN_UPLOAD}
            BEIN_RESOURCE=${BEIN_RESOURCE}
            BEIN_AWS_PROJECT_REGION=${BEIN_AWS_PROJECT_REGION}
            BEIN_AWS_COGNITO_REGION=${BEIN_AWS_COGNITO_REGION}
            BEIN_AWS_USER_POOLS_ID=${BEIN_AWS_USER_POOLS_ID}
            BEIN_AWS_USER_POOLS_WEB_CLIENT_ID=${BEIN_AWS_USER_POOLS_WEB_CLIENT_ID}
            BEIN_CHAT_DEEPLINK=${BEIN_CHAT_DEEPLINK}
            BEIN_CHAT_SOCKET=${BEIN_CHAT_SOCKET}
            APP_VERSION=${APP_VERSION}
            APP_GROUP_PACKAGE_NAME_IOS=${APP_GROUP_PACKAGE_NAME_IOS}
            APP_GROUP_PACKAGE_NAME_ANDROID=${APP_GROUP_PACKAGE_NAME_ANDROID}
            SCHEME_NAME_IOS=${SCHEME_NAME_IOS}
            EOL
      - run:
          name: Decode the google-services.json from Contexts
          command: echo $GOOGLE_SERVICES_Android | base64 --decode > android/app/google-services.json
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: Install Bundle
          command: cd android && bundle install
      - run:
          name: Fastlane Build and Deploy to Diawi
          command: cd android && bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release-unsigned.apk

workflows:
  version: 2
  Staging_iOS-Android:
    jobs:
      - iOS-Approval:
          type: approval
      - Android-Approval:
          type: approval
      - ios-stg:
          filters:
            branches:
              only: /^staging.*$/
          context:
            - bein-group-stg
            - bein-group-stg-ios
          requires:
            - iOS-Approval

      - android-stg:
          filters:
            branches:
              only: /^staging.*$/
          context:
            - bein-group-stg
            - bein-group-stg-android
          requires:
            - Android-Approval

  Production_iOS-Android:
    jobs:
      - ios-pro:
          filters:
            branches:
              only: /^master.*$/
          context:
            - bein-group-pro
            - bein-group-pro-ios
      - android-pro:
          filters:
            branches:
              only: /^master.*$/
          context:
            - bein-group-pro
            - bein-group-pro-android
