const postTypes = {
  // post detail
  SET_POST_DETAIL_REPLYING_COMMENT: 'post/SET_POST_DETAIL_REPLYING_COMMENT',

  // saga
  SET_SCROLL_TO_LATEST_ITEM: 'post/SET_SCROLL_TO_LATEST_ITEM',
  GET_POST_DETAIL: 'post/GET_POST_DETAIL',
  SET_SCROLL_TO_COMMENTS_POSITION: 'post/SET_SCROLL_TO_COMMENTS_POSITION',

  LOADING_GET_POST_DETAIL: 'post/LOADING_GET_POST_DETAIL',
  SET_COMMENT_ERROR_CODE: 'post/SET_COMMENT_ERROR_CODE',
};

export default postTypes;
