const groupsKeySelector = {
  groupDetail: {
    group: 'groups.groupDetail.group',
    can_setting: 'groups.groupDetail.can_setting',
    can_manage_member: 'groups.groupDetail.can_manage_member',
    join_status: 'groups.groupDetail.join_status',
    total_pending_members: 'groups.groupDetail.total_pending_members',
  },
  yourGroupsSearchData: 'groups.yourGroupsSearch',
  yourGroupsTreeData: 'groups.yourGroupsTree',
  yourGroupsListData: 'groups.yourGroupsList',
  groupSearch: 'groups.groupSearch',
  refreshingGroupPosts: 'groups.refreshingGroupPosts',
  loadingGroupMember: 'groups.loadingGroupMember',
  groupMember: 'groups.groupMember',
  groupSearchMembers: 'groups.groupSearchMembers',
  selectedUsers: 'groups.selectedUsers',
  users: 'groups.users',
  posts: 'groups.posts',
  addSuccess: 'groups.addSuccess',
  userAddedCount: 'groups.userAddedCount',
  joinedGroups: 'groups.joinedGroups',
  loadingJoinedGroups: 'groups.loadingJoinedGroups',
  loadingGroupDetail: 'groups.loadingGroupDetail',
  loadingPage: 'groups.loadingPage',
  pendingMemberRequests: 'groups.pendingMemberRequests',
  loadingAvatar: 'groups.loadingAvatar',
  loadingCover: 'groups.loadingCover',
  joinedCommunities: 'groups.joinedCommunities.data',
  managedCommunities: 'groups.managedCommunities',
  discoverCommunitiesData: 'groups.discoverCommunities',
  loadingCommunities: 'groups.communities.loading',
  communityDetail: 'groups.communityDetail',
  isGettingInfoDetail: 'groups.isGettingInfoDetail',
  communityMembers: 'groups.communityMembers',
  communitySearchMembers: 'groups.communitySearchMembers',
  discoverGroups: 'groups.discoverGroups',
  communityMemberRequests: 'groups.communityMemberRequests',
  permission: {
    categories: 'groups.permissionScheme.categories',
    systemScheme: 'groups.permissionScheme.systemScheme',
  },
};

export default groupsKeySelector;
