const groupsTypes = {
  SET_JOINED_GROUPS: 'groups/SET_JOINED_GROUPS',
  SET_LOADING_JOINED_GROUPS: 'groups/SET_LOADING_JOINED_GROUPS',
  SET_LOADING_GROUP_DETAIL: 'groups/SET_LOADING_GROUP_DETAIL',
  SET_GROUP_DETAIL: 'groups/SET_GROUP_DETAIL',
  SET_GROUP_POSTS: 'groups/SET_GROUP_POSTS',
  SET_LOADING_GROUP_POSTS: 'groups/SET_LOADING_GROUP_POSTS',
  SELECT_GROUP_DETAIL: 'groups/SELECT_GROUP_DETAIL',

  //for saga
  GET_JOINED_GROUPS: 'groups/GET_JOINED_GROUPS',
  GET_GROUP_DETAIL: 'groups/GET_GROUP_DETAIL',
  GET_GROUP_POSTS: 'groups/GET_GROUP_POSTS',
  EDIT_GROUP_DETAIL: 'groups/EDIT_GROUP_DETAIL',
};

export default groupsTypes;
