const groupsTypes = {
  SET_PRIVACY_MODAL_OPEN: 'groups/SET_PRIVACY_MODAL_OPEN',

  GET_JOINED_GROUPS: 'groups/GET_JOINED_GROUPS',
  SET_JOINED_GROUPS: 'groups/SET_JOINED_GROUPS',

  CLEAR_GROUP_MEMBER: 'groups/CLEAR_GROUP_MEMBER',
  SET_GROUP_MEMBER: 'groups/SET_GROUP_MEMBER',
  GET_GROUP_MEMBER: 'groups/GET_GROUP_MEMBER',
  SET_LOADING_GROUP_MEMBER: 'groups/SET_LOADING_GROUP_MEMBER',

  SET_GROUP_DETAIL: 'groups/SET_GROUP_DETAIL',
  GET_GROUP_DETAIL: 'groups/GET_GROUP_DETAIL',
  EDIT_GROUP_DETAIL: 'groups/EDIT_GROUP_DETAIL',

  GET_GROUP_POSTS: 'groups/GET_GROUP_POSTS',
  SET_GROUP_POSTS: 'groups/SET_GROUP_POSTS',
  SET_EXTRA_GROUP_POSTS: 'groups/SET_EXTRA_GROUP_POSTS',
  MERGE_EXTRA_GROUP_POSTS: 'groups/MERGE_EXTRA_GROUP_POSTS',
  CLEAR_GROUP_POSTS: 'groups/CLEAR_GROUP_POSTS',

  GET_JOINABLE_USERS: 'groups/GET_JOINABLE_USERS',
  SET_JOINABLE_USERS: 'groups/SET_JOINABLE_USERS',
  SET_EXTRA_JOINABLE_USERS: 'groups/SET_EXTRA_JOINABLE_USERS',
  MERGE_EXTRA_JOINABLE_USERS: 'groups/MERGE_EXTRA_JOINABLE_USERS',
  SELECT_JOINABLE_USERS: 'groups/SELECT_JOINABLE_USERS',
  CLEAR_SELECTED_USERS: 'groups/CLEAR_SELECTED_USERS',
  RESET_JOINABLE_USERS: 'groups/RESET_JOINABLE_USERS',
  SET_ADD_MEMBERS_MESSAGE: 'groups/SET_ADD_MEMBERS_MESSAGE',
  CLEAR_ADD_MEMBERS_MESSAGE: 'groups/CLEAR_ADD_MEMBERS_MESSAGE',

  ADD_MEMBERS: 'groups/ADD_MEMBERS',
  JOIN_NEW_GROUP: 'group/JOIN_NEW_GROUP',
  CANCEL_JOIN_GROUP: 'group/CANCEL_JOIN_GROUP',
  LEAVE_GROUP: 'group/LEAVE_GROUP',

  SET_GROUP_ADMIN: 'groups/SET_GROUP_ADMIN',
  REMOVE_GROUP_ADMIN: 'groups/REMOVE_GROUP_ADMIN',

  UPLOAD_IMAGE: 'groups/UPLOAD_IMAGE',

  SET_LOADING_AVATAR: 'groups/SET_LOADING_AVATAR',
  SET_LOADING_COVER: 'groups/SET_LOADING_COVER',
  SET_LOADING_PAGE: 'groups/SET_LOADING_PAGE',

  SET_GROUP_SEARCH: 'groups/SET_GROUP_SEARCH',
  GET_GROUP_SEARCH: 'groups/GET_GROUP_SEARCH',

  REMOVE_MEMBER: 'groups/REMOVE_MEMBER',

  GET_MEMBER_REQUESTS: 'groups/GET_MEMBER_REQUESTS',
  SET_MEMBER_REQUESTS: 'groups/SET_MEMBER_REQUESTS',
  CLEAR_ALL_MEMBER_REQUESTS: 'groups/CLEAR_ALL_MEMBER_REQUESTS',
  APPROVE_SINGLE_MEMBER_REQUEST: 'groups/APPROVE_SINGLE_MEMBER_REQUEST',
  APPROVE_ALL_MEMBER_REQUESTS: 'groups/APPROVE_ALL_MEMBER_REQUESTS',
  DECLINE_SINGLE_MEMBER_REQUEST: 'groups/DECLINE_SINGLE_MEMBER_REQUEST',
  DECLINE_ALL_MEMBER_REQUESTS: 'groups/DECLINE_ALL_MEMBER_REQUESTS',
};

export default groupsTypes;
