export const ROLE_SCOPE = {
  COMMUNITY: 'COMMUNITY',
  GROUP: 'GROUP',
};

export const ROLE_TYPE = {
  COMMUNITY_ADMIN: 'COMMUNITY_ADMIN',
  GROUP_ADMIN: 'GROUP_ADMIN',
  MEMBER: 'MEMBER',
  CREATOR: 'CREATOR',
};
