const menuTypes = {
  SET_LANGUAGE_MODAL_OPEN: 'menu/SET_LANGUAGE_MODAL_OPEN',
  SET_MY_PROFILE: 'menu/SET_MY_PROFILE',
  SELECT_MY_PROFILE: 'menu/SELECT_MY_PROFILE',
  SET_SELECTED_PROFILE: 'menu/SET_SELECTED_PROFILE',
  SELECTED_PROFILE: 'menu/SELECTED_PROFILE',
  EDIT_MY_PROFILE: 'menu/EDIT_MY_PROFILE',
  UPLOAD_IMAGE: 'menu/UPLOAD_IMAGE',

  GET_MY_PROFILE: 'menu/GET_MY_PROFILE',
  GET_SELECTED_PROFILE: 'menu/GET_SELECTED_PROFILE',

  SET_LOADING_AVATAR: 'menu/SET_LOADING_AVATAR',
  SET_LOADING_COVER: 'menu/SET_LOADING_COVER',
};

export default menuTypes;
