const menuTypes = {
  SET_LANGUAGE_MODAL_OPEN: 'menu/SET_LANGUAGE_MODAL_OPEN',

  SET_MY_PROFILE: 'menu/SET_MY_PROFILE',
  EDIT_MY_PROFILE: 'menu/EDIT_MY_PROFILE',

  UPLOAD_IMAGE: 'menu/UPLOAD_IMAGE',

  GET_MY_PROFILE: 'menu/GET_MY_PROFILE',
  SET_EMAIL_EDIT_ERROR: 'menu/SET_EMAIL_EDIT_ERROR',
  SET_PHONE_NUMBER_EDIT_ERROR: 'menu/SET_PHONE_NUMBER_EDIT_ERROR',

  GET_USER_PROFILE: 'menu/GET_USER_PROFILE',
  SET_USER_PROFILE: 'menu/SET_USER_PROFILE',
  SET_SHOW_USER_NOT_FOUND: 'menu/SET_SHOW_USER_NOT_FOUND',
  CLEAR_USER_PROFILE: 'menu/CLEAR_USER_PROFILE',

  SET_LOADING_AVATAR: 'menu/SET_LOADING_AVATAR',
  SET_LOADING_COVER: 'menu/SET_LOADING_COVER',
};

export default menuTypes;
