const noInternetTypes = {
  SET_IS_INTERNET_REACHABLE: 'noInternet/SET_IS_INTERNET_REACHABLE',
  CHECK_IS_INTERNET_REACHABLE: 'noInternet/CHECK_IS_INTERNET_REACHABLE',
  SET_SYSTEM_ISSUE: 'noInternet/SET_SYSTEM_ISSUE',
  SHOW_SYSTEM_ISSUE_THEN_LOGOUT: 'noInternet/SHOW_SYSTEM_ISSUE_THEN_LOGOUT',
  HIDE_SYSTEM_ISSUE_AND_LOGOUT: 'noInternet/HIDE_SYSTEM_ISSUE_AND_LOGOUT',
};

export default noInternetTypes;
