const mainTabStack = {
  newsfeed: 'newsfeed',
  // 'conversation-list': ConversationsList,
  conversation: 'conversation',
  'conversation-detail': 'conversation-detail',
  'create-conversation': 'create-conversation',
  'chat-group-members': 'chat-group-members',
  'add-members': 'add-members',
  // 'group-list': Groups,
  'group-detail': 'group-detail',
  'group-about': 'group-about',
  'group-members': 'group-members',
  'group-files': 'group-files',
  'create-post': 'create-post',
  'create-comment': 'create-comment',
  'post-select-audience': 'post-select-audience',
  'post-select-image': 'post-select-image',
  'post-detail': 'post-detail',
  'group-admin': 'group-admin',
  'general-info': 'general-info',
  'edit-group-description': 'edit-group-description',
  'user-profile': 'user-profile',
  'invite-members': 'invite-members',
  'user-edit': 'user-edit',
  // menu: Menu,
  'component-collection': 'component-collection',
  'account-settings': 'account-settings',
  'security-and-login': 'security-and-login',
  'change-password': 'change-password',
  'edit-basic-info': 'edit-basic-info',
  // notification: Notification,
  'not-select-notification': 'not-select-notification',
};

export default mainTabStack;
