export default {
  INIT_CHAT: 'chat/INIT_CHAT',
  SET_UNREAD_CHANNELS: 'chat/SET_UNREAD_CHANNELS',
  HANDLE_CHAT_EVENT: 'chat/HANDLE_CHAT_EVENT',
  UPDATE_CHANNEL_NOTIFICATION_COUNT: 'chat/UPDATE_CHANNEL_NOTIFICATION_COUNT',
};
