const notificationsTypes = {
  SET_NOTIFICATIONS: 'notifications/SET_NOTIFICATIONS',
  ADD_NEW_NOTIFICATIONS: 'notifications/ADD_NEW_NOTIFICATIONS',
  SET_LOADING_NOTIFICATIONS: 'notifications/SET_LOADING_NOTIFICATIONS',
  CONCAT_NOTICATIONS: 'notifications/CONCAT_NOTICATIONS',
  SET_NO_MORE_NOTIFICATION: 'notifications/SET_NO_MORE_NOTIFICATION',
  SET_IS_LOADING_MORE: 'notifications/SET_IS_LOADING_MORE',

  GET_NOTIFICATIONS: 'notifications/GET_NOTIFICATIONS',
  MARK_AS_READ_ALL: 'notifications/MARK_AS_READ_ALL',
  MARK_AS_SEEN_ALL: 'notifications/MARK_AS_SEEN_ALL',
  MARK_AS_READ: 'notifications/MARK_AS_READ',
  LOADMORE: 'notifications/LOADMORE',
  LOAD_NEW_NOTIFICATIONS: 'notifications/LOAD_NEW_NOTIFICATIONS',
  DELETE_NOTIFICATIONS: 'notifications/DELETE_NOTIFICATIONS',
};

export default notificationsTypes;
