export const INIT_CHAT = 'chat/INIT_CHAT';
export const HANDLE_EVENT = 'chat/HANDLE_EVENT';
export const GET_DATA = 'chat/GET_DATA';
export const SET_DATA = 'chat/SET_DATA';
export const SET_EXTRA_DATA = 'chat/SET_EXTRA_DATA';
export const MERGE_EXTRA_DATA = 'chat/MERGE_EXTRA_DATA';
export const RESET_DATA = 'chat/RESET_DATA';

export const SELECT_CONVERSATION = 'chat/SELECT_CONVERSATION';
export const SEARCH_CONVERSATIONS = 'chat/SEARCH_CONVERSATIONS';
export const SEND_MESSAGE = 'chat/SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'chat/SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILED = 'chat/SEND_MESSAGE_FAILED';
export const RETRY_SEND_MESSAGE = 'chat/RETRY_SEND_MESSAGE';
export const GET_CONVERSATION_DETAIL = 'chat/GET_CONVERSATION_DETAIL';
export const SET_CONVERSATION_DETAIL = 'chat/SET_CONVERSATION_DETAIL';
export const GET_GROUP_ROLES = 'chat/GET_GROUP_ROLES';
export const SET_GROUP_ROLES = 'chat/SET_GROUP_ROLES';
export const GET_SUBSCRIPTIONS = 'chat/GET_SUBSCRIPTIONS';
export const SET_SUBSCRIPTIONS = 'chat/SET_SUBSCRIPTIONS';
export const READ_SUBCRIPTIONS = 'chat/READ_SUBCRIPTIONS';

export const REACT_MESSAGE = 'chat/REACT_MESSAGE';
export const SELECT_USER = 'chat/SELECT_USER';
export const CLEAR_SELECTED_USERS = 'chat/CLEAR_SELECTED_USERS';
export const CREATE_CONVERSATION = 'chat/CREATE_CONVERSATION';
export const CREATE_CONVERSATION_SUCCESS = 'chat/CREATE_CONVERSATION_SUCCESS';
export const ADD_NEW_MESSAGE = 'chat/ADD_NEW_MESSAGE';
export const UPDATE_CONVERSATION_NAME = 'chat/UPDATE_CONVERSATION_NAME';
export const REMOVE_MEMBER = 'chat/REMOVE_MEMBER';
export const REMOVE_MEMBER_SUCCESS = 'chat/REMOVE_MEMBER_SUCCESS';
export const KICK_ME_OUT = 'chat/KICK_ME_OUT';
export const UPLOAD_FILE = 'chat/UPLOAD_FILE';

//mention
export const SET_MENTION_SEARCH_KEY = 'post/SET_MENTION_SEARCH_KEY';
export const GET_MENTION_USERS = 'chat/GET_MENTION_USERS';
export const SET_MENTION_USERS = 'chat/SET_MENTION_USERS';
export const GET_CHAT_PERMISSIONS = 'chat/GET_CHAT_PERMISSIONS';
export const SET_CHAT_PERMISSIONS = 'chat/SET_CHAT_PERMISSIONS';
