export const SET_CONVERSATION_LOADING = 'chat/SET_CONVERSATION_LOADING';
export const HANDLE_CONVERSATIONS_EVENT = 'chat/HANDLE_CONVERSATIONS_EVENT';
export const SET_CONVERSATIONS = 'chat/SET_CONVERSATIONS';
export const SELECT_CONVERSATION = 'chat/SELECT_CONVERSATION';
export const SET_MESSAGES = 'chat/SET_MESSAGES';
export const SEND_MESSAGE = 'chat/SEND_MESSAGE';
export const REACT_MESSAGE = 'chat/REACT_MESSAGE';
