export enum TrackingEvent {
  CONTENT_READ = 'Content Read',
  CONTENT_PUBLISHED = 'Content Published',
  SCHEDULE = 'Schedule',
  EMOJI_REACTED = 'Emoji Reacted',
  COMMENT_ADDED = 'Comment Added',
  IMPORTANT_MARKED = 'Important Marked',
  PERSONAL_PRIVACY_CHANGED = 'Personal Privacy Changed',
  INVITATION_PRIVACY_CHANGED = 'Invitation Privacy Changed',
  AVATAR_CHANGED = 'Avatar Changed',
  AVATAR_PROCESS_DROPPED = 'Avatar Process Dropped',
  COVER_PHOTO_CHANGED = 'Cover Photo Changed',
  COMMUNITY_NOTI_CHANGED = 'Community Noti Changed',
  GROUP_NOTI_CHANGED = 'Group Noti Changed',
  ALL_NOTI_VIEWED = 'All Noti Viewed',
  UNREAD_NOTI_VIEWED = 'Unread Noti Viewed',
  MENTION_NOTI_VIEWED = 'Mention Noti Viewed',
  IMPORTANT_NOTI_VIEWED = 'Important Noti Viewed',
  SPECIFIC_NOTI_CHANGED = 'Specific Noti Changed',
  GROUP_NOTI_ENABLED = 'Group Noti Enabled',
  HOME_NAVIGATED = 'Home Navigated',
  COMMUNITIES_NAVIGATED = 'Communities Navigated',
  NOTIFICATION_NAVIGATED = 'Notifications Navigated',
  MENUS_NAVIGATED = 'Menu Navigated',
  BASIC_INFO_UPDATED = 'Basic Info Updated',
  SIGNED_IN = 'Signed In',
  SIGNED_UP = 'Signed Up',
  CONTACT_INFO_UPDATED = 'Contact Info Updated',
  PASSWORD_CHANGED = 'Password Changed',
  WORK_INFO_UPDATED = 'Work Info Updated',
  OWN_PROFILE_VIEWED = 'Own Profile Viewed',
  BADGES_SAVED = 'Badges Saved',
  USER_BLOCKED = 'User Blocked',
  ANOTHER_PROFILE_VIEWED = 'Another Profile Viewed',
  MASTER_NOTI_CHANGED = 'Master Noti Changed',
  NOTIFICATION_REMOVED = 'Notification Removed',
  NOTIFICATION_OPENED = 'Notification Opened',
}

export enum TrackingEventContentReadAction {
  BODY = 'body',
  SEE_MORE = 'see_more',
  CONTENT_HEADER = 'content_header',
  COMMENT = 'comment',
  SERIES_ITEM = 'series_item',
  NOTIFICATION = 'notification',
}
