const menuTypes = {
  SET_LANGUAGE_MODAL_OPEN: 'menu/SET_LANGUAGE_MODAL_OPEN',

  UPLOAD_IMAGE: 'menu/UPLOAD_IMAGE',

  SET_EMAIL_EDIT_ERROR: 'menu/SET_EMAIL_EDIT_ERROR',
  SET_PHONE_NUMBER_EDIT_ERROR: 'menu/SET_PHONE_NUMBER_EDIT_ERROR',
  SEARCH_COUNTRY_CODE: 'menu/SEARCH_COUNTRY_CODE',
  SEARCH_LOCATION: 'menu/SEARCH_LOCATION',

  SET_LOADING_AVATAR: 'menu/SET_LOADING_AVATAR',
  SET_LOADING_COVER: 'menu/SET_LOADING_COVER',

};

export default menuTypes;
