const menuTypes = {
  SET_LANGUAGE_MODAL_OPEN: 'menu/SET_LANGUAGE_MODAL_OPEN',

  GET_MY_PROFILE: 'menu/GET_MY_PROFILE',
  SET_MY_PROFILE: 'menu/SET_MY_PROFILE',
  EDIT_MY_PROFILE: 'menu/EDIT_MY_PROFILE',

  GET_MY_WORK_EXPERIENCE: 'menu/GET_MY_WORK_EXPERIENCE',
  SET_MY_WORK_EXPERIENCE: 'menu/SET_MY_WORK_EXPERIENCE',
  ADD_WORK_EXPERIENCE: 'menu/ADD_WORK_EXPERIENCE',
  EDIT_WORK_EXPERIENCE: 'menu/EDIT_WORK_EXPERIENCE',
  DELETE_WORK_EXPERIENCE: 'menu/DELETE_WORK_EXPERIENCE',
  SET_SELECTED_WORK_ITEM: 'menu/SET_SELECTED_WORK_ITEM',

  UPLOAD_IMAGE: 'menu/UPLOAD_IMAGE',

  SET_EMAIL_EDIT_ERROR: 'menu/SET_EMAIL_EDIT_ERROR',
  SET_PHONE_NUMBER_EDIT_ERROR: 'menu/SET_PHONE_NUMBER_EDIT_ERROR',
  SEARCH_COUNTRY_CODE: 'menu/SEARCH_COUNTRY_CODE',
  SEARCH_LOCATION: 'menu/SEARCH_LOCATION',

  SET_LOADING_AVATAR: 'menu/SET_LOADING_AVATAR',
  SET_LOADING_COVER: 'menu/SET_LOADING_COVER',

  GET_USER_WORK_EXPERIENCE: 'menu/GET_USER_WORK_EXPERIENCE',
  SET_USER_WORK_EXPERIENCE: 'menu/SET_USER_WORK_EXPERIENCE',
};

export default menuTypes;
