export const FETCH_SETTING = 'common/FETCH_SETTING';
export const FETCH_SETTING_SUCCESS = 'common/FETCH_SETTING_SUCCESS';
export const FETCH_SETTING_ERROR = 'common/FETCH_SETTING_ERROR';

export const SET_MODAL = 'common/SET_MODAL';
export const SHOW_MODAL = 'common/SHOW_MODAL';
export const HIDE_MODAL = 'common/HIDE_MODAL';

export const SHOW_ALERT = 'common/SHOW_ALERT';
export const HIDE_ALERT = 'common/HIDE_ALERT';
export const SHOW_ALERT_NEW_FEATURE = 'common/SHOW_ALERT_NEW_FEATURE';
export const HIDE_ALERT_NEW_FEATURE = 'common/HIDE_ALERT_NEW_FEATURE';
export const SHOW_LOADING = 'common/SHOW_LOADING';
export const HIDE_LOADING = 'common/HIDE_LOADING';

export const SHOW_HIDE_TOAST_MESSAGE = 'common/SHOW_HIDE_TOAST_MESSAGE';
export const SET_TOAST_MESSAGE = 'common/SET_TOAST_MESSAGE';
export const CLEAR_TOAST_MESSAGE = 'common/CLEAR_TOAST_MESSAGE';
export const FOCUS_SEARCH_INPUT = 'common/FOCUS_SEARCH_INPUT';

export const SHOW_REACTION_DETAIL_BOTTOM_SHEET =
  'common/SHOW_REACTION_DETAIL_BOTTOM_SHEET';
export const CLEAR_REACTION_DETAIL_BOTTOM_SHEET =
  'common/CLEAR_REACTION_DETAIL_BOTTOM_SHEET';

export const SET_SHOW_REACTION_BOTTOM_SHEET =
  'common/SET_SHOW_REACTION_BOTTOM_SHEET';

export const SET_USER_PROFILE_PREVIEW_BOTTOM_SHEET =
  'common/SET_USER_PROFILE_PREVIEW_BOTTOM_SHEET';
export const SHOW_USER_PROFILE_PREVIEW_BOTTOM_SHEET =
  'common/SHOW_USER_PROFILE_PREVIEW_BOTTOM_SHEET';
export const HIDE_USER_PROFILE_PREVIEW_BOTTOM_SHEET =
  'common/HIDE_USER_PROFILE_PREVIEW_BOTTOM_SHEET';

export const SHOW_SEEN_PEOPLE_LIST_BOTTOM_SHEET =
  'common/SHOW_SEEN_PEOPLE_LIST_BOTTOM_SHEET';
