const homeTypes = {
  SET_HOME_POSTS: 'home/SET_HOME_POSTS',
  SET_REFRESHING_HOME_POSTS: 'home/SET_REFRESHING_HOME_POSTS',
  SET_LOADING_HOME_POSTS: 'home/SET_LOADING_HOME_POSTS',
  SET_NO_MORE_HOME_POSTS: 'home/SET_NO_MORE_HOME_POSTS',
  SET_NEWSFEED_SEARCH: 'home/SET_NEWSFEED_SEARCH',
  CLEAR_NEWSFEED_SEARCH: 'home/CLEAR_NEWSFEED_SEARCH',
  SET_NEWSFEED_SEARCH_FILTER: 'home/SET_NEWSFEED_SEARCH_FILTER',
  CLEAR_NEWSFEED_SEARCH_FILTER: 'home/CLEAR_NEWSFEED_SEARCH_FILTER',

  // for saga
  GET_HOME_POSTS: 'home/GET_HOME_POSTS',
  GET_SEARCH_POSTS: 'home/GET_SEARCH_POSTS',
};
export default homeTypes;
