const homeTypes = {
  SET_HOME_POSTS: 'home/SET_HOME_POSTS',
  SET_HOME_POSTS_IMPORTANT_COUNT: 'home/SET_HOME_POSTS_IMPORTANT_COUNT',
  SET_REFRESHING_HOME_POSTS: 'home/SET_REFRESHING_HOME_POSTS',
  SET_LOADING_HOME_POSTS: 'home/SET_LOADING_HOME_POSTS',
  SET_NO_MORE_HOME_POSTS: 'home/SET_NO_MORE_HOME_POSTS',

  // for saga
  GET_HOME_POSTS: 'home/GET_HOME_POSTS',
};
export default homeTypes;
