import {IGroupDetail} from '~/interfaces/IGroup';
import {POST_DETAIL} from './post';

export const groupDetailData: IGroupDetail = {
  group: {
    id: 1,
    parent_id: null,
    name: 'EVOL Community',
    slug: 'evol-community-1641809088',
    description: 'The greatest community ever',
    level: 0,
    parents: null,
    owner_id: 1,
    icon: '',
    background_img_url: null,
    group_type: 'COMPANY',
    privacy: 'PUBLIC',
    chat_id: 'rpq3unai7i8ztprmoz97rdjr7w',
    created_at: '2022-01-10T10:04:48.685Z',
    updated_at: '2022-01-10T10:04:48.928Z',
    deleted_at: null,
    user_count: 25,
  },
  join_status: 2,
  can_setting: false,
  can_manage_member: false,
  total_pending_members: 0,
};

export const adminDetail = {
  id: 1,
  username: 'testmember',
  fullname: 'Test Name Admin',
  avatar:
    'https://bein-entity-attribute-stg.s3.ap-southeast-1.amazonaws.com/user/avatar/Avatar_Profile.png',
  chat_user_id: 'mdp9rococ3d83qk9nbrybxay3e',
  is_admin: true,
  custom_role_ids: [],
  roles: [
    {
      data_values: {
        id: '23a07c64-27d7-4438-a17d-9aae7bbbd4df',
        name: 'Admin',
        type: 'GROUP_ADMIN',
        permissions: [
          'view_group_profile',
          'view_group_members',
          'view_message',
          'view_message_history',
          'send_message',
          'send_files',
          'send_images',
          'react',
          'send_tickers',
          'mention_all_here',
          'pin_message',
          'view_post',
          'view_post_statistic',
          'create_post',
          'view_related_post',
          'report_member',
          'manage_member',
          'setting',
          'approve_post',
          'report_post',
          'mark_important_post',
          'delete_post',
          'edit_group_profile',
          'change_parent_group',
          'delete_message',
        ],
      },
      previous_data_values: {
        id: '23a07c64-27d7-4438-a17d-9aae7bbbd4df',
        name: 'Admin',
        type: 'GROUP_ADMIN',
        permissions: [
          'view_group_profile',
          'view_group_members',
          'view_message',
          'view_message_history',
          'send_message',
          'send_files',
          'send_images',
          'react',
          'send_tickers',
          'mention_all_here',
          'pin_message',
          'view_post',
          'view_post_statistic',
          'create_post',
          'view_related_post',
          'report_member',
          'manage_member',
          'setting',
          'approve_post',
          'report_post',
          'mark_important_post',
          'delete_post',
          'edit_group_profile',
          'change_parent_group',
          'delete_message',
        ],
      },
      changed: {},
      options: {
        is_new_record: false,
        schema: 'bein',
        schema_delimiter: '',
        include_validated: true,
        raw: true,
        attributes: ['id', 'name', 'type', 'permissions'],
      },
      is_new_record: false,
    },
  ],
};

export const memberDetail = {
  id: 2,
  username: 'testmember',
  fullname: 'Test Name Member',
  avatar:
    'https://bein-entity-attribute-sandbox.s3.ap-southeast-1.amazonaws.com/user/avatar/images/original/26657b00-f704-47e6-9254-9e51d2365ac4.jpg',
  chat_user_id: '4bkzernmdtgb7eiy9yspw3n4ra',
  is_admin: false,
  custom_role_ids: [],
  roles: [],
};

export const memberData = {
  group_admin: {
    name: 'Admin',
    data: [adminDetail, adminDetail, adminDetail],
    user_count: 3,
  },
  group_member: {
    name: 'Member',
    data: [memberDetail, memberDetail, memberDetail, memberDetail],
    user_count: 4,
  },
};

export const discoverGroup = {
  id: 24,
  parent_id: 22,
  name: 'Bein Back-end Bein Group',
  slug: '504bb9ec-3e69-472a-8d2d-74cbbac75ca9-1641835590',
  description: null,
  level: 4,
  created_by: 1,
  icon: null,
  background_img_url: null,
  privacy: 'PUBLIC',
  chat_id: 'aj1s4cktxjg53npisjetdspyxy',
  scheme_id: 'd9e5362a-ca6b-42c7-8530-a3b2aa67f15a',
  created_at: '2022-01-10T17:26:29.895Z',
  updated_at: '2022-01-10T17:47:44.883Z',
  deleted_at: null,
  user_count: 7,
  join_status: 1,
};

/**
 * Selecting status:
 * [ ] EVOL Community
 *  - [x] Bein Community
 *  -  - [x] Bein Product Team
 */
export const GROUP_TREE_WITH_SELECTING = {
  '1': false,
  '10': {
    id: 10,
    parent_id: 1,
    name: 'Bein Community',
    slug: '863b7fce-2a88-4441-aa24-4803f7b6d1ec-1641834908',
    description: null,
    level: 1,
    parents: [1],
    owner_id: 1,
    icon: null,
    background_img_url: null,
    group_type: 'GENERIC',
    privacy: 'PUBLIC',
    chat_id: 'nc1m1i78fpdaiktp7bdzdnntgh',
    created_at: '2022-01-10T17:15:08.123Z',
    updated_at: '2022-01-10T17:15:08.592Z',
    deleted_at: null,
    children: [],
    user_count: '19',
    uiId: 'tree_0_0',
    parentUiId: 'tree_0',
    hide: false,
    uiLevel: 1,
    isCollapsing: false,
    isChecked: true,
    childrenUiIds: ['tree_0_0_0'],
  },
  '17': {
    id: 17,
    parent_id: 10,
    name: 'Bein Product Team',
    slug: 'cd99ab19-a7bf-461b-9b0e-35f809774821-1641835298',
    description: null,
    level: 2,
    parents: [1, 10],
    owner_id: 1,
    icon: null,
    background_img_url: null,
    group_type: 'GENERIC',
    privacy: 'PUBLIC',
    chat_id: '3typp5m3b3r7byuu5q3fjqmaaa',
    created_at: '2022-01-10T17:21:38.026Z',
    updated_at: '2022-01-10T17:47:03.538Z',
    deleted_at: null,
    children: [],
    user_count: '18',
    uiId: 'tree_0_0_0',
    parentUiId: 'tree_0_0',
    hide: false,
    uiLevel: 2,
    isCollapsing: false,
    isChecked: true,
    childrenUiIds: [],
  },
};

/**
 * Mock data of tree
 *  - EVOL Community
 *  - - Bein Community
 *  - - - Bein Product Team
 */
export const GROUP_TREE = {
  id: 1,
  parent_id: null,
  name: 'EVOL Community',
  slug: 'evol-community-1641809088',
  description: 'The greatest community ever',
  level: 0,
  parents: null,
  owner_id: 1,
  icon: '',
  background_img_url: null,
  group_type: 'COMPANY',
  privacy: 'PUBLIC',
  chat_id: 'rpq3unai7i8ztprmoz97rdjr7w',
  created_at: '2022-01-10T10:04:48.685Z',
  updated_at: '2022-01-10T10:04:48.928Z',
  deleted_at: null,
  children: [
    {
      id: 10,
      parent_id: 1,
      name: 'Bein Community',
      slug: '863b7fce-2a88-4441-aa24-4803f7b6d1ec-1641834908',
      description: null,
      level: 1,
      parents: [1],
      owner_id: 1,
      icon: null,
      background_img_url: null,
      group_type: 'GENERIC',
      privacy: 'PUBLIC',
      chat_id: 'nc1m1i78fpdaiktp7bdzdnntgh',
      created_at: '2022-01-10T17:15:08.123Z',
      updated_at: '2022-01-10T17:15:08.592Z',
      deleted_at: null,
      children: [
        {
          id: 17,
          parent_id: 10,
          name: 'Bein Product Team',
          slug: 'cd99ab19-a7bf-461b-9b0e-35f809774821-1641835298',
          description: null,
          level: 2,
          parents: [1, 10],
          owner_id: 1,
          icon: null,
          background_img_url: null,
          group_type: 'GENERIC',
          privacy: 'PUBLIC',
          chat_id: '3typp5m3b3r7byuu5q3fjqmaaa',
          created_at: '2022-01-10T17:21:38.026Z',
          updated_at: '2022-01-10T17:47:03.538Z',
          deleted_at: null,
          children: [],
          user_count: '18',
        },
      ],
      user_count: '19',
    },
  ],
  user_count: '25',
  unique: 'ad26adcf-2827-42e2-9f3e-19ae2192b6d0',
};

// contains 25 (appConfig.recordsPerPage) data for testing
export const groupPostData = [
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
  POST_DETAIL,
];
