export default {
  SET_ROOT_SCREEN_NAME: 'app/SET_ROOT_SCREEN_NAME',
  SET_DRAWER_VISIBLE: 'app/SET_DRAWER_VISIBLE',
  SET_SHOW_ERROR: 'app/SET_SHOW_ERROR',
  SET_DEBUGGER_VISIBLE: 'app/SET_DEBUGGER_VISIBLE',
};
