export default {
  GET_CONFIGS: 'app/GET_CONFIGS',
  SET_CONFIGS: 'app/SET_CONFIGS',
  GET_LINK_PREVIEW: 'app/GET_LINK_PREVIEW',
  SET_LINK_PREVIEW: 'app/SET_LINK_PREVIEW',
};

// export const SETUP_PUSH_TOKEN = 'app/SETUP_PUSH_TOKEN';
// export const COPY_DEVICE_TOKEN = 'app/COPY_DEVICE_TOKEN';
