export const GET_CONFIGS = 'app/GET_CONFIGS';
export const SET_CONFIGS = 'app/SET_CONFIGS';
export const SETUP_PUSH_TOKEN = 'app/SETUP_PUSH_TOKEN';
export const COPY_DEVICE_TOKEN = 'app/COPY_DEVICE_TOKEN';
export const SET_HEADER_FLASH_MESSAGE = 'app/SET_HEADER_FLASH_MESSAGE';
export const CLEAR_HEADER_FLASH_MESSAGE = 'app/CLEAR_HEADER_FLASH_MESSAGE';
export const SHOW_HEADER_FLASH_MESSAGE = 'app/SHOW_HEADER_FLASH_MESSAGE';
