const homeTypes = {
  SET_NEWSFEED_SEARCH: 'home/SET_NEWSFEED_SEARCH',
  SET_NEWSFEED_SEARCH_RECENT_KEYWORDS:
    'home/SET_NEWSFEED_SEARCH_RECENT_KEYWORDS',
  CLEAR_ALL_NEWSFEED_SEARCH: 'home/CLEAR_ALL_NEWSFEED_SEARCH',

  // for saga
  GET_SEARCH_POSTS: 'home/GET_SEARCH_POSTS',
  GET_RECENT_SEARCH_KEYWORDS: 'GET_RECENT_SEARCH_KEYWORDS',
  DELETE_CLEAR_RECENT_SEARCH_KEYWORDS: 'DELETE_CLEAR_RECENT_SEARCH_KEYWORDS',
  DELETE_RECENT_SEARCH_KEYWORD_BY_ID: 'DELETE_RECENT_SEARCH_KEYWORD_BY_ID',
};
export default homeTypes;
