const groupsKeySelector = {
  groupDetail: {
    group: 'groups.groupDetail.group',
    joinStatus: 'groups.groupDetail.joinStatus',
  },
  yourGroupsSearchData: 'groups.yourGroupsSearch',
  yourGroupsTreeData: 'groups.yourGroupsTree',
  yourGroupsListData: 'groups.yourGroupsList',
  groupSearch: 'groups.groupSearch',
  refreshingGroupPosts: 'groups.refreshingGroupPosts',
  loadingGroupMember: 'groups.loadingGroupMember',
  groupMembers: 'groups.groupMembers',
  groupSearchMembers: 'groups.groupSearchMembers',
  selectedUsers: 'groups.selectedUsers',
  users: 'groups.users',
  posts: 'groups.posts',
  addSuccess: 'groups.addSuccess',
  userAddedCount: 'groups.userAddedCount',
  joinedGroups: 'groups.joinedGroups',
  loadingJoinedGroups: 'groups.loadingJoinedGroups',
  loadingGroupDetail: 'groups.loadingGroupDetail',
  isLoadingGroupDetailError: 'groups.isLoadingGroupDetailError',
  loadingPage: 'groups.loadingPage',
  groupMemberRequests: 'groups.groupMemberRequests',
  loadingAvatar: 'groups.loadingAvatar',
  loadingCover: 'groups.loadingCover',
  joinedCommunities: 'groups.joinedCommunities',
  loadingCommunities: 'groups.communities.loading',
  communityDetail: 'groups.communityDetail',
  communityMembers: 'groups.communityMembers',
  communitySearchMembers: 'groups.communitySearchMembers',
  communityMemberRequests: 'groups.communityMemberRequests',
  communitySearch: 'groups.communitySearch',
  globalSearch: 'groups.globalSearch',
  myPermissions: 'groups.myPermissions',
  joinedAllGroups: 'groups.joinedAllGroups',
  managed: 'groups.managed',
};

export default groupsKeySelector;
