const groupsTypes = {
  GET_GROUP_SEARCH_MEMBERS: 'groups/GET_GROUP_SEARCH_MEMBERS',
  SET_GROUP_SEARCH_MEMBERS: 'groups/SET_GROUP_SEARCH_MEMBERS',
  CLEAR_GROUP_SEARCH_MEMBERS: 'groups/CLEAR_GROUP_SEARCH_MEMBERS',

  GET_JOINABLE_USERS: 'groups/GET_JOINABLE_USERS',
  SET_JOINABLE_USERS: 'groups/SET_JOINABLE_USERS',
  SET_EXTRA_JOINABLE_USERS: 'groups/SET_EXTRA_JOINABLE_USERS',
  MERGE_EXTRA_JOINABLE_USERS: 'groups/MERGE_EXTRA_JOINABLE_USERS',
  SET_MERGE_EXTRA_JOINABLE_USERS: 'groups/SET_MERGE_EXTRA_JOINABLE_USERS',
  SELECT_JOINABLE_USERS: 'groups/SELECT_JOINABLE_USERS',
  CLEAR_SELECTED_USERS: 'groups/CLEAR_SELECTED_USERS',
  RESET_JOINABLE_USERS: 'groups/RESET_JOINABLE_USERS',

  ADD_MEMBERS: 'groups/ADD_MEMBERS',
  REMOVE_MEMBER: 'groups/REMOVE_MEMBER',
  CANCEL_JOIN_GROUP: 'group/CANCEL_JOIN_GROUP',

  UPLOAD_IMAGE: 'groups/UPLOAD_IMAGE',

  // COMMUNITY
  GET_JOINED_COMMUNITIES: 'groups/GET_JOINED_COMMUNITIES',
  GET_COMMUNITY_GROUPS: 'groups/GET_COMMUNITY_GROUPS',
  GET_DISCOVER_GROUPS: 'groups/GET_DISCOVER_GROUPS',
  SET_DISCOVER_GROUPS: 'groups/SET_DISCOVER_GROUPS',
  EDIT_DISCOVER_GROUP_ITEM: 'groups/EDIT_DISCOVER_GROUP_ITEM',
  JOIN_COMMUNITY: 'groups/JOIN_COMMUNITY',
  CANCEL_JOIN_COMMUNITY: 'groups/CANCEL_JOIN_COMMUNITY',

  GET_JOINED_ALL_GROUPS: 'groups/GET_JOINED_ALL_GROUPS',

  GET_GLOBAL_SEARCH: 'groups/GET_GLOBAL_SEARCH',
  SET_GLOBAL_SEARCH: 'groups/SET_GLOBAL_SEARCH',
  RESET_GLOBAL_SEARCH: 'groups/RESET_GLOBAL_SEARCH',
};

export default groupsTypes;
