---
name: build-android-production
on:
  push:
    tags:
      - "*v*"

jobs:
  build-android-production:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: self-hosted
    timeout-minutes: 120
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: ci/prepare-build-resources
        run: |
          npm run clone-secret
          npm run clone-build-resources
          npm run prepare-resources

      - name: ci/build-android-production
        run: npm run build-android-production

  trigger-codemagic-build:
    if: startsWith(github.ref, 'refs/tags/ci-v')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Codemagic build
        uses: codemagic-ci-cd/trigger-codemagic-workflow-action@v1.0.0
        with:
          app-id: 64d5def4bbb38bd520b3dc80
          workflow-id: build-android-production
          token: ${{ secrets.CODEMAGIC_API_TOKEN }}
