name: Merge Event Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  process_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Merge Details
        env:
          NOTICE_BUILD_WEBHOOK: ${{ secrets.NOTICE_BUILD_WEBHOOK }}
        run: |
          echo "Target Branch: ${{ github.event.pull_request.base.ref }}"
          echo "Source Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Merge Commit SHA: ${{ github.event.pull_request.merge_commit_sha }}"
          echo "Number of Commits: ${{ github.event.pull_request.commits }}"
          
          if [[ "${{ github.event.pull_request.base.ref }}" == staging* ]]; then
            bundle exec fastlane notice_build_task env:"stg"
          elif [[ "${{ github.event.pull_request.base.ref }}" == release* ]]; then
            bundle exec fastlane notice_build_task env:"rel"
          elif [[ "${{ github.event.pull_request.base.ref }}" == master* ]]; then
            bundle exec fastlane notice_build_task env:"pro"
          elif [[ "${{ github.event.pull_request.base.ref }}" == test* ]]; then
            bundle exec fastlane notice_build_task env:"stg"
          else
            echo "No matching conditions for branch ${GITHUB_REF}"
          fi
